services:
  db:
    image: mysql:8.0
    container_name: giglio-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: giglio
      MYSQL_USER: giglio
      MYSQL_PASSWORD: giglio
    ports:
      - "3307:3306" # GRANT ALL PRIVILEGES ON *.* TO 'giglio'@'%' WITH GRANT OPTION; (piccolo remind)
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - giglio_mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: giglio-app
    environment:
      DATABASE_URL: mysql://giglio:giglio@db:3306/giglio
      REST_PORT: 3000
      GRPC_URL: 0.0.0.0:50051
    ports:
      - "3000:3000"
      - "50051:50051"
    depends_on:
      db:
        condition: service_healthy

volumes:
  giglio_mysql_data:
